services:
  postgres:
    image: postgres:16-alpine@sha256:d898b0b78a2627cb4ee63464a14efc9d296884f1b28c841b0ab7d7c42f1ebb9f
    environment:
      POSTGRES_DB: pfetl
      POSTGRES_USER: pfetl_user
      POSTGRES_PASSWORD: pfetl_password
    ports:
      - "5432:5432"
    volumes:
      - ./etl/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pfetl_user -d pfetl"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s

  demo:
    build:
      context: .
      dockerfile: Dockerfile.demo
    environment:
      DATABASE_URL: postgresql://pfetl_user:pfetl_password@postgres:5432/pfetl
      PFETL_NO_EGRESS: "1"
      LC_ALL: C.UTF-8
      TZ: UTC
      PFETL_PLAIN: "1"
    volumes:
      - ./build:/app/build
    command: ["python3", "cli.py", "demo", "--docker", "--out", "/app/build"]
    depends_on:
      postgres:
        condition: service_healthy