services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: pfetl
      POSTGRES_USER: pfetl_user
      POSTGRES_PASSWORD: pfetl_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./etl/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pfetl_user -d pfetl"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s

volumes:
  postgres_data: